### ISSUE TITLE
Support for scala 2.13

### ISSUE THREAD

**Issue by Tochemey** [taymyr/lagom-openapi#33] opened 2020-03-04 08:26 UTC
I would like to know when the scala 2.13 artifact will be out

**Comment by ihostage** [comment] 2020-03-04 08:32
Hi, @Tochemey 😉 
We have a plan publish release this week after implement #20.
But you can try a `1.1.0-SNAPSHOT` version from [Sonatype Snapshots](https://oss.sonatype.org/content/repositories/snapshots/) repository.

Closed as duplicate of https://github.com/taymyr/lagom-openapi/issues/21

**Closed by ihostage** 2020-03-04 08:32 UTC
